/*
 * 
 * File: Configurations.java
 * 
 * Copyright (C) 2015, Nuance Communications Inc. All Rights Reserved.
 * 
 */

package com.nuance.nina.configurations;
/**
 * Class that defines the application variables
 * This class is generated by a script before donwloading and the variables are populated from the user account provided by Nuance.
 *
 */
public class Configurations
{
	/**
	 * NMAID ID
	 */
	public static String NMAID_ID = "ConUHackCo001_ConUHackApp001_20160111_170747";
	/**
	 * NMAID Key as string
	 */
	public static final String NMAID_KEY_STRING = "0xd9 0x5f 0xbe 0xeb 0x1a 0xf1 0x6c 0xfe 0x60 0xce 0x40 0xbe 0x8f 0xbe 0x2d 0xa7 0x0d 0x16 0xe5 0x74 0x70 0x96 0x96 0x53 0xf1 0xcd 0xdd 0xfb 0xe9 0x1a 0x49 0xc1 0x74 0x25 0x90 0x9b 0x75 0x05 0xde 0xd8 0x4d 0xab 0xc8 0x8e 0x3c 0xce 0xfd 0x71 0x2c 0x99 0x13 0xb5 0x3e 0x32 0x49 0xa6 0x05 0x75 0xa1 0xd9 0x3b 0xa3 0xe9 0xd8";
	/**
	 * Application Name
	 */
	public static String APPLICATION_NAME = "ConUHackApp001";
	/**
	 * Application version
	 */
	public static String APPLICATION_VERSION = "0.0";
	/**===========================
	 * Company Name
	 */
	public static String COMPANY_NAME = "ConUHackCo001";

	/**
	 * Server IP address or host name to connect to
	 */
	public static String GATEWAY_HOST = "nim-rd.nuance.mobi";

	/**
	 * Port number
	 */
	public static int GATEWAY_PORT = 443;

	/**
	 * Gateway SSL 
	 */
	public static boolean GATEWAY_USE_SSL = true;

	/**
	 * Gateway SSL certificate
	 */
	public static boolean GATEWAY_VERIFY_SSL_CERTIFICATE = false;

	/**
	 * Server Application name
	 */
	public static String SERVER_APPLICATION_NAME = "NinaCloud";

	/**
	 * Default Nina voice for TTS prompts. The spelling should be exactly the same of a voice enabled for your application by Nuance
	 */
	public static String TTS_VOICE_NAME = "Samantha";
	/**
	 * Default Nina locale for TTS prompts. The spelling should be exactly the same of a locale enabled for your application by Nuance
	 */
	public static String TTS_VOICE_LOCALE = "en";
}
